### ISSUE TITLE
Bug：无法登录

### ISSUE THREAD

**Issue by duangai** [pagenote/pagenote#124]
![image](https://user-images.githubusercontent.com/34684428/155246557-41b41c3b-9b0f-4d08-a5c8-8ecb2851df0d.png)

点击登录

![image](https://user-images.githubusercontent.com/34684428/155246621-8beaa4ff-00da-4e80-865a-b1de7d32d68e.png)

在跳出的弹窗中，显示已登录，点击id，完成登录。

![image](https://user-images.githubusercontent.com/34684428/155246737-e3572ac9-aa78-4a44-939c-64a071b50eb8.png)

关闭弹窗，刷新浏览器，依然显示未登录，且已解锁功能不能用。

**Comment by rowthan** [comment]
感谢反馈，已修复，请重置密码后重试。
