### ISSUE TITLE
sponsor not work

### ISSUE THREAD

**Issue by zhicheng-ning** [pagenote/pagenote#136]
I have sponsored 40 RMB to Pagenote through Alipay, but it doesn't seem to work
My email：simaqinsheng@gmail.com
![image](https://user-images.githubusercontent.com/39022409/162129057-62769245-aaec-4dd7-b303-570a5274c206.png)

**Comment by rowthan** [comment]
replied by email. check the email please.

**Comment by rowthan** [comment]
You can also bind your transition by yourself in this [site](https://pagenote.cn/pro-plan)
![image](https://user-images.githubusercontent.com/12638456/162164051-37f861c2-4763-4f16-a120-8f5f203bdafe.png)

**Comment by zhicheng-ning** [comment]
> like this

![a227a7d014eb88f682d21d51c463198](https://user-images.githubusercontent.com/39022409/162167187-b0ae2fe7-f102-4c19-a6ea-e98d77f7ade2.jpg)

**Comment by zhicheng-ning** [comment]
I'm sorry, it looks like my email is wrong.
