### ISSUE TITLE
github第三方授权可以少要权限吗

### ISSUE THREAD

**Issue by TheKingOfGhost** [pagenote/pagenote#143]
![图片](https://user-images.githubusercontent.com/37435759/168764713-2492412f-6b21-487a-86fd-0683b46e9cce.png)
要了很多敏感的权限，让我不敢授权
`- View and manage users blocked by you
- View and manage your email addresses
- View and manage users you follow
- Create and modify a user's gists and comments.
- View and manage your public GPG keys
- View and manage your interaction limits
- View and manage your Git SSH keys
- View your subscription plan on GitHub
- Manage a user's profile settings.
- View and manage your starred repositories
- View and manage your watched repositories

 `

**Comment by rowthan** [comment]
谢谢反馈，已删除此类授权要求，仅保留获取用户邮件地址授权诉求。

目前也只用到了邮件信息，没有读取、修改过任何其他信息，请放心。

对于历史已授权用户，可以在 https://github.com/settings/apps/authorizations 删除授权后，重新授权登录；或待下一次授权时，会自动清空其他未使用的权限。

之所以要求了其他权限，是因为当时在开发一个功能：
1. 将 PAGENOTE 做的标记，自动存放到用户的一个git仓库下，借助 GitHub 的版本管理能力，实现数据版本化。
2. 将 PAGENOTE 做的标记，借助 GitHub page 的能力，自动生成一个用户的个人主页，可以在公网环境下，分享笔记。

以上功能暂时 pending 中，待启动开发完成后，再新加权限授权。
