### ISSUE TITLE
VIP无法登录了 作者能否帮忙修复一下？

### ISSUE THREAD

**Issue by iamaaronhu** [pagenote/pagenote#165]
VIP无法登录了 作者能否抽空帮忙修复一下？
![image](https://user-images.githubusercontent.com/96708393/233594453-f79f64d6-6748-49fc-bf8e-0f0799d9793d.png)

**Comment by rowthan** [comment]
已修复 请升级至0.26.5以上版本 如还有问题请留言

**Comment by iamaaronhu** [comment]
Thanks. 感恩~~~
