### ISSUE TITLE
求助：部分网页站点启用插件只能作用一定时间，无法一直生效

### ISSUE THREAD

**Issue by cyk2018** [pagenote/pagenote#166]
作者您好！
我在https://github.com/rowthan/developer.pagenote.cn/issues/36 提出了一个问题，并向您发送了一份邮件。今日发现此repo，不知二者有什么区别，我大致看了代码库developer.pagenote.cn，希望在设置中添加一个功能即将某个域名下的所有网页的tabState.active都设置成true。这样在此域名下就不需要每次点击启用。相当于是对其建立了一个whiteList

**Comment by rowthan** [comment]
1. 关于几个仓库的说明见：[https://developer.pagenote.cn/developer/project](https://developer.pagenote.cn/developer/project)
2. 目前默认所有网站都是白名单，都会默认启动；可以通过黑名单控制默认不启动。你是遇到哪些网站默认没有启用吗？如果是，请提供一下浏览器插件版本号、浏览器类型、未默认启动的网页URL。

**Comment by cyk2018** [comment]
> 1. 关于几个仓库的说明见：https://developer.pagenote.cn/developer/project
> 2. 目前默认所有网站都是白名单，都会默认启动；可以通过黑名单控制默认不启动。你是遇到哪些网站默认没有启用吗？如果是，请提供一下浏览器插件版本号、浏览器类型、未默认启动的网页URL。

感谢作者的回复！
浏览器插件版本号：0.26.6.2
浏览器类型：Edge 114.0.1823.41
问题网页：
http://tai-e.pascal-lab.net/pa5.html#_2-3tai-e-%E4%B8%AD%E4%BD%A0%E9%9C%80%E8%A6%81%E4%BA%86%E8%A7%A3%E7%9A%84%E7%B1%BB

**Comment by rowthan** [comment]
0.27.4 支持对单个网页、域名禁用设置。
